# Packages Python

In [1]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##
Note: you may need to restart the kernel to use updated packages.





==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base -c defaults conda





  environment location: C:\Users\Lenovo\anaconda3\envs\hacktiv8-env

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.11.8          |   py38haa95532_0         148 KB
    ------------------------------------------------------------
                                           Total:         148 KB

The following packages will be UPDATED:

  certifi            pkgs/main/noarch::certifi-2020.6.20-p~ --> pkgs/main/win-64::certifi-2020.11.8-py38haa95532_0




certifi-2020.11.8    | 148 KB    |            |   0% 
certifi-2020.11.8    | 148 KB    | #          |  11% 
certifi-2020.11.8    | 148 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


In [2]:
conda list

# packages in environment at C:\Users\Lenovo\anaconda3\envs\hacktiv8-env:
#
# Name                    Version                   Build  Channel
argon2-cffi               20.1.0           py38he774522_1  

Note: you may need to restart the kernel to use updated packages.
async_generator           1.10                       py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
backcall                  0.2.0                      py_0  
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
ca-certificates           2020.10.14                    0  
certifi                   2020.11.8        py38haa95532_0  
cffi                      1.14.3           py38hcd4344a_2  
colorama                  0.4.4                      py_0  
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
entr

In [4]:
conda install numpy

Solving environment: ...working... 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/noarch::ipywidgets==7.5.1=py_1
  - defaults/win-64::jupyter==1.0.0=py38_7
  - defaults/win-64::widgetsnbextension==3.5.1=py38_0
done

## Package Plan ##

  environment location: C:\Users\Lenovo\anaconda3\envs\hacktiv8-env

  added / updated specs:
    - numpy


The following NEW packages will be INSTALLED:

  notebook           pkgs/main/win-64::notebook-6.1.4-py38_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base -c defaults conda


DEBUG menuinst_win32:__init__(198): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\Lenovo\anaconda3\envs\hacktiv8-env', env_name: 'hacktiv8-env', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\Lenovo\anaconda3\python.exe, args are ['C:\\Users\\Lenovo\\anaconda3\\cwp.py', 'C:\\Users\\Lenovo\\anaconda3\\envs\\hacktiv8-env', 'C:\\Users\\Lenovo\\anaconda3\\envs\\hacktiv8-env\\python.exe', 'C:\\Users\\Lenovo\\anaconda3\\envs\\hacktiv8-env\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']


In [5]:
import numpy as np

In [6]:
print("numpy ver:", np.__version__)

numpy ver: 1.19.2


In [76]:
# define array using np.array
arr_int = np.array([[1,2,3],[4,5,6]])
print(arr_int)
print("type:", type(arr_int), "shape:", arr_int.shape)
print("axis 0:", arr_int.shape[0], "axis 1:", arr_int.shape[1])
print(len(arr_int))

arr1d_float = np.array([.1,.2,.3,.4])
print(arr1d_float)
print("type:", type(arr1d_float), "shape:", arr1d_float.shape)
print("axis [0]:", arr1d_float.shape[0])
print(len(arr1d_float))

arr3d_int = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(arr3d_int)
print("type:", type(arr3d_int), "shape:", arr3d_int.shape)
print(
    "axis 0:", arr3d_int.shape[0], 
    "axis 1:", arr3d_int.shape[1],
    "axis 2:", arr3d_int.shape[2]
)
print(len(arr3d_int))

[[1 2 3]
 [4 5 6]]
type: <class 'numpy.ndarray'> shape: (2, 3)
axis 0: 2 axis 1: 3
2
[0.1 0.2 0.3 0.4]
type: <class 'numpy.ndarray'> shape: (4,)
axis [0]: 4
4
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
type: <class 'numpy.ndarray'> shape: (2, 2, 2)
axis 0: 2 axis 1: 2 axis 2: 2
2


In [77]:
arr_zeros = np.zeros((2,3))
print(arr_zeros, arr_zeros.dtype, type(arr_zeros), arr_zeros.shape)

arr_ones = np.ones((2,4))
print(arr_ones, arr_ones.dtype, type(arr_ones), arr_ones.shape)

arr_arange = np.arange(1, 2, .1)
print(arr_arange, arr_arange.dtype, type(arr_arange), arr_arange.shape)

arr_empty = np.empty((100, 100))
print(arr_empty, arr_empty.dtype, type(arr_empty), arr_empty.shape)

[[0. 0. 0.]
 [0. 0. 0.]] float64 <class 'numpy.ndarray'> (2, 3)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64 <class 'numpy.ndarray'> (2, 4)
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9] float64 <class 'numpy.ndarray'> (10,)
[[ 1.06555321e-311  1.06559273e-311 -4.61307932e+019 ...  0.00000000e+000
  -1.80778254e-121  1.06559075e-311]
 [ 1.06559077e-311  3.60767295e-072  0.00000000e+000 ...  1.45252838e-087
   1.06558934e-311  1.06559111e-311]
 [-5.83343944e-077  0.00000000e+000  0.00000000e+000 ...  1.06556975e-311
   1.06559124e-311  1.05992523e+102]
 ...
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]] float64 <class 'numpy.ndarray'> (100, 100)


In [78]:
dummy_list = [[1,2,3], [4,5,6]]
print ("list:", dummy_list)
print ("array:", arr_int)

#indexing
print(dummy_list[0][0], dummy_list[0][:2])
print(arr_int[0, 0], arr_int[0, :2])
print(arr_int[::-1, ::-1])

list: [[1, 2, 3], [4, 5, 6]]
array: [[1 2 3]
 [4 5 6]]
1 [1, 2]
1 [1 2]
[[6 5 4]
 [3 2 1]]


In [79]:
#ndimimension and size of ndarray
print("num of dimension:", arr_int.ndim)
print("num of dimension:", arr3d_int.ndim)

print("num of size:", arr_int.size)
print("num of size:", arr3d_int.size)

num of dimension: 2
num of dimension: 3
num of size: 6
num of size: 8


In [80]:
#flatten
print("before flatten:", arr_int)
print("after flatten:", arr_int.flatten())

before flatten: [[1 2 3]
 [4 5 6]]
after flatten: [1 2 3 4 5 6]


In [81]:
np.array([1, 2, 3]).shape, np.array([[1, 2, 3]]).shape, np.array([[10], [2]]).shape

((3,), (1, 3), (2, 1))

In [82]:
#append and delete
print(np.append(arr1d_float, [10,11,12]))
print(np.append(arr_int, [[10,11,12]], axis=0))
print(np.append(arr_int, [[10], [11]], axis=1))
print(np.append(arr_int,arr_int, axis=0))

print(np.concatenate([arr_int,arr_int], axis=1))

print(arr3d_int)
print(np.delete(arr3d_int, -1, axis=1))
print(np.delete(arr3d_int, 0, axis=1))
print(np.delete(arr3d_int, 1, axis=1))

print(np.delete(arr3d_int, -1, axis=0))
print(np.delete(arr3d_int, 0, axis=0))
print(np.delete(arr3d_int, 1, axis=0))

[ 0.1  0.2  0.3  0.4 10.  11.  12. ]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]]

 [[5 6]]]
[[[3 4]]

 [[7 8]]]
[[[1 2]]

 [[5 6]]]
[[[1 2]
  [3 4]]]
[[[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]]


In [83]:
#reshape
print(arr3d_int)
print(arr3d_int.shape)
print(np.reshape(arr3d_int, (2,2,2)))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [84]:
print(arr1d_float.shape)

arr2d_float = arr1d_float[:, np.newaxis]
print(arr2d_float, arr2d_float.shape)

print(arr1d_float[None])

(4,)
[[0.1]
 [0.2]
 [0.3]
 [0.4]] (4, 1)
[[0.1 0.2 0.3 0.4]]


# Mathematics Operations

In [97]:
print(dummy_list + dummy_list)
print(arr_int + arr_int)
print(arr_int * 10)
print(arr_int * arr_int)
print(arr_int / arr_int)

print(arr_int.sum(axis=0))
print(arr_int.sum(axis=1, keepdims=True))
print(arr_int.sum(axis=0, keepdims=True))
print(arr_int.sum(keepdims=True))

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[10 20 30]
 [40 50 60]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[5 7 9]
[[ 6]
 [15]]
[[5 7 9]]
[[21]]


In [105]:
print (arr1d_float, arr1d_float)
print(np.dot(arr1d_float, arr1d_float))

print(arr_int)
print(np.dot(arr_int, arr_int.T))

print(arr_int)
print(np.matmul(arr_int, arr_int.T))

print(arr_int)
print(np.matmul(arr_int.T, arr_int))
print(np.einsum("ij, jk->ji", arr_int))

[0.1 0.2 0.3 0.4] [0.1 0.2 0.3 0.4]
0.3
[[1 2 3]
 [4 5 6]]
[[14 32]
 [32 77]]
[[1 2 3]
 [4 5 6]]
[[14 32]
 [32 77]]
[[1 2 3]
 [4 5 6]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]


ValueError: more operands provided to einstein sum function than specified in the subscripts string

In [116]:
np.random.seed(11111)

print(np.random.randint(10, size=(2,3)))
print(np.random.uniform(size=(2,3)))
print(np.random.randn(2,3))
print(np.random.normal(2.,3, size=(5,1)))

[[4 9 6]
 [4 5 6]]
[[0.82876716 0.03982066 0.88557674]
 [0.56628677 0.19393237 0.14565492]]
[[ 0.87934863 -2.41514016  1.2408447 ]
 [ 0.6047445   0.58081538 -0.84691576]]
[[5.22517781]
 [6.46188642]
 [2.62225082]
 [2.41654891]
 [4.62259563]]
